### ISSUE TITLE
[s3-proxy] Provide S3 via secret

### ISSUE THREAD

**Issue by MatthiasLohr** [oxyno-zeta/helm-charts#17]
Currently, it does not seem to be possible to provide the S3 credentials via secret. The `env` parameter only allows for key/value pairs, `secretFiles` mount files, they cannot be parsed since s3-proxy expects the only content of a credentials file to be the actual value, not a document containing multiple values.

Am I missing something? If not, could you please provide this feature? Thanks!

Best regards
Matthias

**Comment by oxyno-zeta** [comment]
Hello,

Yes you can provide S3 credentials via secrets of course ;) . I'm not a big fan of values like that in env. But I wanted to offer people maximum flexibility.

Here is an example of values that you can have:

```yaml
# Secret files for secrets declaration
# Will be mounted in /proxy/secret-files
secretFiles:
  # Example
  # my-syper-secret-file: my-awesome-secret
  AWS_SECRET_ACCESS_KEY: MY SUPER SECRET VALUE

configFiles:
  config.yaml: |-
    # Targets
    targets:
      - name: first-bucket
        ## Mount point
        mount:
          path:
            - /
        ## Bucket configuration
        bucket:
          name: super-bucket
          prefix:
          region: eu-west-1
          s3Endpoint:
          disableSSL: false
          credentials:
            accessKey:
              env: AWS_ACCESS_KEY_ID
            secretKey:
              path: /proxy/secret-files/AWS_SECRET_ACCESS_KEY
```

In that example, you can have the access key in env and secret access key by file (and in a k8s secret).

You can put all values you want in secret.

The secret will have all keys mounted as files into `/proxy/secret-files`.

PS: There is a comment error in the chart :( . I will fix them as soon as possible. Paths in this example are corrects.

Regards,

**Comment by MatthiasLohr** [comment]
Sorry, I don't get this. I have a Secret `testbucket` with following contents:
```
AWS_ACCESS_KEY_ID: ****
AWS_SECRET_ACCESS_KEY: ******
```

I configued:
```
secretFiles:
  aws-credentials: testbucket
```

The file only contains the string `testbucket`, not the value of the Kubernetes `Secret` object.

What I need: I want to get `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` from a Kubernetes Secret object, residing in my cluster.

**Comment by oxyno-zeta** [comment]
Ah I was thinking you will add secret with the chart.
This feature is available too.

You can use:
```yaml
existingSecret: testbucket
```

And have the s3 configuration like this:
```yaml
          credentials:
            accessKey:
              env: /proxy/secret-files/AWS_ACCESS_KEY_ID
            secretKey:
              path: /proxy/secret-files/AWS_SECRET_ACCESS_KEY
```

This should work as you need.
